[package]
name = "polar"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A command-line calculator that can also convert between units."
repository = "https://github.com/skycloudd/polar"
readme = "README.md"
exclude = [".github"]

[dependencies]
